# See https://domluna.github.io/JuliaFormatter.jl/stable/ for a list of options
margin = 200
remove_extra_newlines = true
trailing_zero = false
join_lines_based_on_source = true
whitespace_in_kwargs = false